import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthButtons from "@/components/AuthButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pl" className="bg-neutral-950 text-neutral-100">
      <body>
        <header className="border-b border-neutral-800 bg-neutral-900/60">
          <div className="mx-auto max-w-4xl px-4 py-3 flex items-center justify-between">
            <a href="/" className="font-semibold">BidCars</a>
            <AuthButtons />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
